### ISSUE TITLE
[Enhancement] Add submitter name to email subject

### ISSUE THREAD

**Issue by eryno** [helpmeabstract/helpmeabstract#19]
## Suggested Enhancement

Add submitter name to the subject in the "Abstract Submitted For Review" email.
## Goal

I end up with an inbox of emails with the same subject. Having the name in the subject would 
1. Help me differentiate between different mails
2. Likely motivate me to open emails sooner, because I either think, "Oh, I know them and I want to help!" or "I don't know this person, maybe they're a new speaker! I want to help!"

**Comment by greydnls** [comment]
👍  This is now live.

**Comment by eryno** [comment]
Ask and you shall receive! Thanks, @kayladnls.
