### ISSUE TITLE
Speaker names overlap on mobile

### ISSUE THREAD

**Issue by eryno** [helpmeabstract/helpmeabstract#27]
# Steps to Reproduce
1. Fire up your Android phone
2. Visit http://helpmeabstract.com/
3. Scroll down to the speakers
# Expected Results

It will be beautiful and lovely.
# Actual Results

It is lovely to see people helping people, but their names run into each other and are very difficult to read.

Screenshot:
![screenshot_20160620-164148](https://cloud.githubusercontent.com/assets/691315/16293106/c0db6420-38dc-11e6-86c3-e4ea5e32112a.png)

**Comment by greydnls** [comment]
Removed speaker names... so that oughta fix this. >.<
