### ISSUE TITLE
Unsubscribe functionality missing

### ISSUE THREAD

**Issue by skade** [helpmeabstract/helpmeabstract#28]
Once on the list, it is impossible to unsubscribe and stop receiving messages from helpmeabstract.com.

**Comment by skade** [comment]
@greydnls Do you mind if I rattle on this a little? Sure, I can put a filter on your mails, but I'd prefer to just unsubscribe.

Thanks.

**Comment by greydnls** [comment]
@skade If you would like to work on this that would be great. in the mean time, email me your email and I'll remove you. So sorry I didn't get to this sooner, I've been completely swamped. Email is the same as my github at gmail dot com.

**Comment by greydnls** [comment]
@skade You're unsubscribed from the list. I'll make sure unsubscribe is easier in the future. Thanks.

**Comment by jasonmccreary** [comment]
I would like to unsubscribe as well. Don't see where this functionality has been added so I'm asking humbly here…
