### ISSUE TITLE
Volunteer link is dead

### ISSUE THREAD

**Issue by MattiSG** [helpmeabstract/helpmeabstract#32]
If I click on the `volunteer` button, I get to the `http://helpmeabstract.com/volunteer` page, with yields a 404:

> Not Found
> The requested URL /volunteer was not found on this server.
> Apache/2.4.9 (Ubuntu) Server at helpmeabstract.com Port 80

**Comment by rogeriopradoj** [comment]
As http://helpmeabstract.com/index.php/volunteer quite works (broken assets), I guess the issue is related with Rewrite URL configuration. @greydnls is already taking a look (https://twitter.com/greydnls/status/800338161381609472).

**Comment by greydnls** [comment]
Fixed this.
