### ISSUE TITLE
Homepage Provides No Clue What This Is

### ISSUE THREAD

**Issue by FedgeNo** [helpmeabstract/helpmeabstract#33]
What it says on the tin.

**Comment by greydnls** [comment]
![image](https://cloud.githubusercontent.com/assets/1276798/20528015/82ab285a-b098-11e6-9cc9-ff5b956e5653.png)


This is what's on the homepage. What would you suggest to make it clearer?

**Comment by FedgeNo** [comment]
Sorry, I meant this github repo. The readme.md page doesn't show what it's for at all.
