### ISSUE TITLE
[Idea] Add abstract title to mail notification

### ISSUE THREAD

**Issue by jfversluis** [helpmeabstract/helpmeabstract#43]
While I love the simple idea of hosting the abstracts in a Github Gist, it would be nice to have the subject upfront in the e-mail notification.

As a volunteer I can probably say more useful things on subjects that I am familiar with and right now I have to open each and every abstract to tell.

Are there any more people that think this makes sense?

**Comment by greydnls** [comment]
Just merged in a PR that would make this happen! #59
