### ISSUE TITLE
Long Names Cause Alignment Issues

### ISSUE THREAD

**Issue by colinodell** [helpmeabstract/helpmeabstract#44]
Long names cause the social icons to bump down to a new line which interferes with the left floats:

![image](https://user-images.githubusercontent.com/202034/33623082-d61fc000-d9bd-11e7-92f3-1b8324efdfca.png)

Adding a CSS rule like `.image h3 { height: 4em; }` seems to fix this:

![image](https://user-images.githubusercontent.com/202034/33623117-ed00682e-d9bd-11e7-97c1-f1012b9ae48e.png)

However, styling isn't my thing, so I don't know if this is the best solution.  (If this is acceptable, it seems like an easy PR for somebody :wink:)

**Comment by greydnls** [comment]
This should be addressed now!
