### ISSUE TITLE
Submission form doesn't work

### ISSUE THREAD

**Issue by jonpugh** [helpmeabstract/helpmeabstract#47]
I've been trying the form at "Submit Abstract" under the recommendation of DrupalCon:  http://helpmeabstract.com/submitAbstract

Get nothing but "uh oh, something went wrong"

Thanks!

**Comment by greydnls** [comment]
Thanks for the heads up! I'll take a look at the logs this evening.

**Comment by greydnls** [comment]
This hsould be resolved. Let me know if you have any further issues.

**Comment by Keheira** [comment]
@greydnls I'm now getting this issue as well.
