### ISSUE TITLE
Slim application error while registering as a volunteer

### ISSUE THREAD

**Issue by stevegrunwell** [helpmeabstract/helpmeabstract#53]
I went to volunteer to review abstracts today, but encountered a Slim application error after submitting [the volunteer form](http://helpmeabstract.com/volunteer):

```
Slim Application Error
The application could not run because of the following error:

Details
Type: Doctrine\DBAL\DBALException
Message: An exception occurred while executing 'SELECT COUNT(*) FROM `volunteers` `volunteers` WHERE ()' with params ["MYEMAIL@MYDOMAIN"]: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 1
File: /var/app/current/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php
Line: 91
Trace
#0 /var/app/current/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(701): Doctrine\DBAL\DBALException::driverExceptionDuringQuery(Object(PDOException), 'SELECT COUNT(*)...', Array)
#1 /var/app/current/vendor/doctrine/dbal/lib/Doctrine/DBAL/Query/QueryBuilder.php(204): Doctrine\DBAL\Connection->executeQuery('SELECT COUNT(*)...', Array, Array)
#2 /var/app/current/vendor/vlucas/spot2/lib/Query.php(589): Doctrine\DBAL\Query\QueryBuilder->execute()
#3 /var/app/current/src/Entity/Mapper/Volunteer.php(58): Spot\Query->count()
#4 /var/app/current/public/index.php(62): HelpMeAbstract\Entity\Mapper\Volunteer->findByEmail('steve@stevegrun...')
#5 [internal function]: {closure}()
#6 /var/app/current/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#7 /var/app/current/vendor/slim/slim/Slim/Slim.php(1355): Slim\Route->dispatch()
#8 /var/app/current/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#9 /var/app/current/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#10 /var/app/current/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#11 /var/app/current/vendor/slim/slim/Slim/Slim.php(1300): Slim\Middleware\PrettyExceptions->call()
#12 /var/app/current/public/index.php(143): Slim\Slim->run()
#13 {main}
```

When I cloned the repo, I was able to reproduce it locally: it appears that `HelpMeAbstract\Entity\Mapper\Volunteer::findByEmail()` ends up generating a SQL query with an empty `WHERE` clause:

```sql
SELECT * FROM `volunteers` `volunteers` WHERE ()
```

Upgrading vlucas/spot to `^2.2` (and removing the explicit doctrine/dbal requirement, since it's already required by vlucas/spot) changes the query to use a prepared statement:

```sql
SELECT * FROM `volunteers` WHERE `volunteers`.`email` = ?
```

However, submitting the form with the latest version of vlucas/spot results in a Help Me Abstract-branded "Uh oh, something went wrong" error screen (and my data is not saved to the database):

![screen shot 2018-03-28 at 11 20 37 am](https://user-images.githubusercontent.com/233836/38038891-0e13ce2e-327a-11e8-90c4-2871c0601250.png)

It's likely that it's some combination of dependencies not playing nicely together, but I don't have the time at the moment to troubleshoot further. I wanted to document my findings here, though, in case any other would-be volunteers run into the issue.

**Comment by greydnls** [comment]
This should be fixed now. Thanks for bringing it to my attention!

**Comment by stevegrunwell** [comment]
Can confirm, I was just able to register as a volunteer. Thanks, Graham!
