### ISSUE TITLE
"uh oh, something went wrong" when submitting an abstract

### ISSUE THREAD

**Issue by c10ce** [helpmeabstract/helpmeabstract#58]
# To reproduce

Submit a filled-out form (which POSTs to http://helpmeabstract.com/submitAbstract)

## Expected

A message is displayed to the user that their abstract was received and processed successfully

## Actual

The index page displays, along with a message saying "uh oh, something went wrong"

**Comment by greydnls** [comment]
Sorry about that. Should be resolved now. Thanks for reporting!

**Comment by c10ce** [comment]
Confirmed to be working now!

**Comment by Keheira** [comment]
Can this be opened back up? I'm getting the same error even when all fields are filled in. Could there be some more specific errormessages because I'm not sure where the error is coming from.
