### ISSUE TITLE
Is this down?

### ISSUE THREAD

**Issue by Godley** [helpmeabstract/helpmeabstract#61]
First of all thanks so much for this project - I've used it a couple of times and always really appreciate how easy it makes getting honest feedback.

Is the website backend down at the moment, though? I've tried to submit in the last few days and just got "something went wrong"

**Comment by DjThossi** [comment]
Same here. I just tried to submit but got the same error message. Please reach out to me if you need more details.

**Comment by greydnls** [comment]
Sorry about that. It should be up and running now! Let me know if you have any further issues.
