### ISSUE TITLE
504 Gateway timeout

### ISSUE THREAD

**Issue by antodippo** [helpmeabstract/helpmeabstract#62]
Hello, I've been trying to access the website for the last few hours but I couldn't.
Here are the errors that I get running curl:

```
➜  ~ curl http://helpmeabstract.com -vvv
* Rebuilt URL to: http://helpmeabstract.com/
*   Trying 35.153.25.233...
* TCP_NODELAY set
* Connected to helpmeabstract.com (35.153.25.233) port 80 (#0)
> GET / HTTP/1.1
> Host: helpmeabstract.com
> User-Agent: curl/7.54.0
> Accept: */*
>
< HTTP/1.1 504 GATEWAY_TIMEOUT
< Content-Length: 0
< Connection: keep-alive
<
* Connection #0 to host helpmeabstract.com left intact
```
Same with https.
Thanks!

**Comment by geshan** [comment]
please fix this, ping @greydnls .

**Comment by DjThossi** [comment]
Please fix this, I'd love to hand in another gist, please
https://gist.github.com/DjThossi/ec4cda018c1b4396b24f2df885fc6861

**Comment by greydnls** [comment]
Back up and running! Thanks for your patience!
