### ISSUE TITLE
Submission is coming back with error

### ISSUE THREAD

**Issue by geshan** [helpmeabstract/helpmeabstract#63]
## Error on submission

After filling up all the fields and submitting it is coming back with `uh oh, something went wrong`. Can this be looked into, please?

<img width="1034" alt="Screen Shot 2019-07-31 at 12 48 48 pm" src="https://user-images.githubusercontent.com/170554/62179938-8f75c280-b391-11e9-8557-fa94700306bf.png">

**Comment by stockholmux** [comment]
Same result.

**Comment by antodippo** [comment]
Same here. @greydnls , how can we help?

**Comment by mariano-calandra-xp** [comment]
Same here, is this site still in service?

**Comment by darth-zwergal** [comment]
same here. what a pitty. such an awesome initiative

**Comment by greydnls** [comment]
Thanks for the patience on this. I took a bit of an unannounced hiatus from the internet to handle some personal items. I'll check this out asap.

**Comment by darth-zwergal** [comment]
Hi @greydnls thank you so much for letting us know and for checking!

**Comment by greydnls** [comment]
Just pinging back -- I did look over the weekend. there wasn't anything
glaring in the logs. I'm going to dig in to do some more debugging tomorrow
night. I'll aim to keep this issue updated. Thanks again for the patience.

**Comment by kolawoletech** [comment]
Still not working

**Comment by wilfi** [comment]
Not working still.
